- uk/medium-deep-readonly.md
> [solution] uk/medium-deep-readonly

- uk/medium-diff.md
> [solution] uk/medium-diff

- uk/medium-isnever.md
> [solution] uk/medium-isnever

- uk/medium-replaceall.md
> [solution] uk/medium-replaceall

- uk/medium-return-type.md
> [solution] uk/medium-return-type

- uk/medium-trimleft.md
> [solution] uk/medium-trimleft

- uk/medium-trim.md
> [solution] uk/medium-trim

- uk/medium-tuple-to-union.md
> [solution] uk/medium-tuple-to-union

- uk/medium-type-lookup.md
> [solution] uk/medium-type-lookup

- uk/medium-drop-char.md
> [solution] uk/medium-drop-char

- en/medium-replaceall.md
> consider same chars in a next iteration

- ko/index.md
I started Korean translation and this is my first PR!
I tried to follow the commit convention & branch naming.
If I miss something, please let me know :)
> [solution]: ko/index.md

- ko/easy-awaited.md
After the initial work, I found that there was an update on this challenge recently.
So I added the translation on that update, too.
> [solution]: ko/easy-awaited.md

- ko/warm-hello-world.md
> [solution]: ko/warm-hello-world.md

- ko/easy-exclude.md
> [solution]: ko/easy-exclude.md

- ko/easy-first.md
> [solution]: ko/easy-first.md

- ko/easy-if.md
> [solution]: ko/easy-if.md

- ko/easy-includes.md
I found that there are some issues in this challenge.
I agree that the precise solution in comment section is too hard for easy level. So I just translated the original solution.
> [solution]: ko/easy-includes.md

- ko/easy-pick.md
I left the word in English if there is no standard Korean translation for that word.(Ex. Lookup Type)
> [solution]: ko/easy-pick.md

- ko/easy-push.md
> [solution]: ko/easy-push.md

- ko/easy-readonly.md
> [solution]: ko/easy-readonly.md

- ko/easy-tuple-length.md
> [solution]: ko/easy-tuple-length.md

- ko/easy-tuple-to-object.md
> [solution]: ko/easy-tuple-to-object.md

- _data/i18n.yml
- _data/navigation.yml
- zh/index.md
> add Chinese localisation

- ko/easy-unshift.md
> [solution]: ko/easy-unshift.md

- ko/medium-absolute.md
> [solution]: ko/medium-absolute.md

- ko/medium-append-argument.md
> [solution]: ko/medium-append-argument.md

- ko/medium-camelcase.md
> [solution]: ko/medium-camelcase.md

- ko/medium-capitalize.md
> [solution]: ko/medium-capitalize.md

- ko/medium-chainable-options.md
> [solution]: ko/medium-chainable-options.md

- ko/medium-deep-readonly.md
> [solution]: ko/medium-deep-readonly.md

- ko/medium-diff.md
> [solution]: ko/medium-diff.md

- zh/easy-first.md
> [solution]: zh/easy-first

- zh/easy-if.md
> [solution]: zh/easy-if

- ko/medium-append-to-object.md
> [solution]: ko/medium-append-to-object.md

- zh/easy-includes.md
> [solution]: zh/easy-includes

- zh/easy-pick.md
> [solution]: zh/easy-pick

- zh/easy-push.md
> [solution]: zh/easy-push

- zh/easy-readonly.md
> [solution]: zh/easy-readonly

- uk/easy-unshift.md
> [solution] uk/easy-unshift

- uk/medium-endswith.md
> [solution] uk/medium-endswith

- uk/medium-mutable.md
> [solution] uk/medium-mutable

- zh/easy-tuple-length.md
> [solution]: zh/easy-tuple-length

- zh/easy-tuple-to-object.md
> [solution]: zh/easy-tuple-to-object

- zh/easy-unshift.md
> [solution]: zh/easy-unshift

- ko/medium-drop-char.md
> [solution]: ko/medium-drop-char.md

- ko/medium-endswith.md
> [solution]: ko/medium-endswith.md

- ko/medium-flatten.md
> [solution]: ko/medium-flatten.md

- ko/medium-isunion.md
> [solution]: ko/medium-isunion.md

- ko/medium-isnever.md
> [solution]: ko/medium-isnever.md

- zh/medium-absolute.md
> [solution]: zh/medium-absolute

- zh/medium-append-argument.md
> [solution]: zh/medium-append-argument.md (#191)

- zh/medium-flatten.md
> [solution]: zh/medium-flatten.md (#459)

- ko/medium-kebabcase.md
> [solution]: ko/medium-kebabcase.md

- ko/medium-length-of-string.md
> [solution]: ko/medium-length-of-string.md

- ko/medium-last.md
> [solution]: ko/medium-last.md

- zh/medium-last.md
> [solution]: zh/medium-last.md

- zh/medium-pop.md
> [solution]: zh/medium-pop.md

- .gitignore
- zh/medium-anyof.md
> [solution]: zh/medium-anyof

- ko/medium-merge.md
> [solution]: ko/medium-merge.md

- zh/medium-anyof.md
> [update]: link to the Chinese version

- zh/medium-append-to-object.md
> [solution]: zh/medium-append-to-object

- zh/medium-capitalize.md
> [solution]: zh/medium-capitalize

- zh/medium-deep-readonly.md
> [solution]: zh/medium-deep-readonly.md

- ko/medium-minusone.md
> [solution]: ko/medium-minusone.md

- zh/medium-chainable-options.md
> [solution]: zh/medium-chainable-options.md

- ko/medium-mutable.md
> [solution]: ko/medium-mutable.md

- ko/medium-omit.md
> [solution]: ko/medium-omit.md

- ko/medium-percentage-parser.md
> [solution]: ko/medium-percentage-parser.md

- zh/easy-parameters.md
> [solution]: zh/easy-parameters

- ko/medium-permutation.md
> [solution]: ko/medium-permutation.md

- zh/medium-endswith.md
> [solution]: zh/medium-endswith

- ko/medium-replaceall.md
> [solution]: ko/medium-replaceall.md

- ko/medium-replace.md
> [solution]: ko/medium-replace.md

- ko/medium-remove-index-signature.md
> [solution]: ko/medium-remove-index-signature.md

- ko/medium-readonly-2.md
> [solution]: ko/medium-readonly-2.md

- ko/medium-pop.md
> [solution]: ko/medium-pop.md

- ko/medium-promise-all.md
> [solution]: ko/medium-promise-all.md

- ko/medium-bem-style-string.md
> [solution]: ko/medium-bem-style-string.md

- ko/medium-pickbytype.md
> [solution]: ko/medium-pickbytype.md

- ko/medium-replacekeys.md
> [solution]: ko/medium-replacekeys.md

- ko/medium-reverse.md
> [solution]: ko/medium-reverse.md

- ko/medium-return-type.md
> [solution]: ko/medium-return-type.md

- zh/medium-bem-style-string.md
> [solution]: zh/medium-bem-style-string.md

- zh/medium-chunk.md
> [solution]: zh/medium-chunk.md

- zh/medium-return-type.md
> [solution]:zh/medium-return-type

- en/medium-partial-by-keys.md
> [solution]: en/medium-partial-by-keys.md

- en/medium-required-by-keys.md
> [solution]: en/medium-required-by-keys.md

- en/medium-tuple-to-nested-object.md
> [solution]: en/medium-tuple-to-nested-object.md

- en/medium-object-entries.md
> [solution]: en/medium-object-entries.md

- en/medium-inorder-traversal.md
> [solution]: en/medium-inorder-traversal.md

- en/medium-flip.md
> [solution]: en/medium-flip.md

- zh/medium-drop-char.md
> [solution]:zh/medium-drop-char

- en/medium-readonly-2.md
- zh/medium-readonly-2.md
> [solution]: zh/medium-readonly-2.md

- zh/medium-isnever.md
> [solution]: zh/medium-isnever.md

- zh/medium-tuple-to-union.md
> [solution]: zh/medium-tuple-to-union.md

- zh/medium-type-lookup.md
> [solution]: zh/medium-type-lookup.md

- zh/medium-replace.md
> [solution]: zh/medium-replace.md

- zh/medium-replaceall.md
> [solution]: zh/medium-replaceall.md

- zh/medium-replacekeys.md
> [solution]: zh/medium-replacekeys.md

- zh/medium-flip-arguments.md
> [solution]: zh/medium-flip-arguments.md

- zh/medium-flip.md
> [solution]: zh/medium-flip.md

- zh/medium-lastindexof.md
> [solution]: zh/medium-lastindexof

- zh/medium-trim-right.md
> [solution]: zh/medium-trim-right

- zh/medium-join.md
> [solution]: zh/medium-join

- _data/i18n.yml
- _data/navigation.yml
- ja/index.md
- ja/warm-hello-world.md
Hi! Thanks for your great website! I have translated index.md and the Warm Up Challenge into Japanese and would like to have this merged into the repository.
> Add Japanese translation

- ja/easy-pick.md
> [solution] ja/easy-pick.md

- ja/easy-readonly.md
> [solution] ja/easy-readonly.md

- ja/easy-tuple-to-object.md
> [solution] ja/easy-tuple-to-object.md

- ja/easy-first.md
> [solution] ja/easy-first.md

- ja/easy-tuple-length.md
> [solution] ja/easy-tuple-length.md

- ja/easy-exclude.md
> [solution] ja/easy-exclude.md

- ja/easy-if.md
> [solution] ja/easy-if.md

- ja/easy-awaited.md
> [solution] ja/easy-awaited.md

- ja/easy-parameters.md
> [solution]: ja/easy-parameters.md

- ja/easy-concat.md
> [solution]: ja/easy-concat.md

- ja/easy-push.md
> [solution]: ja/easy-push.md

- ja/easy-includes.md
> [solution]: ja/easy-includes.md

- ja/easy-unshift.md
> [solution]: ja/easy-unshift.md

- zh/medium-mutable.md
>  zh/medium-mutable

- en/easy-tuple-length.md
> [solution] add an alternative solution

- zh/easy-includes.md
> [typo]: zh/easy-includes.md

- zh/easy-tuple-length.md
> [solution]: update zh/easy-tuple-length
